# Generated by Django 4.2.21 on 2025-05-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoring',
            name='max_students',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
