# Generated by Django 4.2.21 on 2025-05-28 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tutoring_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoring',
            name='tutoring_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
    ]
