# Generated by Django 4.2.21 on 2025-06-06 01:17

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_teacher_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.CharField(default=backend.models.generate_unique_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
