# Generated by Django 4.2.21 on 2025-06-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
