# Generated by Django 4.2.21 on 2025-08-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_reservation_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
    ]
