# Generated by Django 4.2.21 on 2025-08-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_teacher_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
    ]
