# Generated by Django 4.2.21 on 2025-08-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_teacher_profile_image_teacher_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comments',
            field=models.TextField(default='No comment.'),
        ),
    ]
