# Generated by Django 4.2.21 on 2025-08-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_reservation_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='comments',
        ),
    ]
